[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/:country"
  to = "/.netlify/functions/m3u-generator/:country"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/m3u-generator"
  status = 200
  force = true